name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Docker images (for backend updates)
        if: runner.os == 'Linux'
        run: |
          cd backend
          docker build -t trackhounds-backend:latest .
          cd ../database
          docker build -t trackhounds-mariadb:latest .

          # Save images as tar files
          mkdir -p frontend/docker-resources
          docker save trackhounds-backend:latest > frontend/docker-resources/backend.tar
          docker save trackhounds-mariadb:latest > frontend/docker-resources/mariadb.tar

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: frontend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
