name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Docker images (for backend updates)
        if: runner.os == 'Linux'
        run: |
          # Create an env file for Docker Compose
          cp frontend/docker-resources/.env.example frontend/docker-resources/.env

          # Build backend image using the main docker-compose.yml
          docker-compose build backend

          # Build or pull MariaDB image
          docker pull mariadb:latest

          # Ensure directories exist
          mkdir -p frontend/docker-resources

          # Copy the docker-compose file to the resources folder if not already there
          cp docker-compose.yml frontend/docker-resources/docker-compose.yml || echo "Compose file already exists"

          # Save images as tar files
          docker save backend:latest > frontend/docker-resources/backend.tar
          docker save mariadb:latest > frontend/docker-resources/mariadb.tar

          # Verify the tar files were created
          ls -la frontend/docker-resources/

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: frontend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
